# Generated by Django 5.2.8 on 2026-03-25 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('screen_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('browser_info', models.JSONField(blank=True, default=dict, null=True)),
                ('suspicious_activities', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('session_data', models.JSONField(blank=True, default=dict, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='proctoring.proctoringsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_focus_lost', 'Window Focus Lost'), ('face_not_detected', 'Face Not Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('suspicious_movement', 'Suspicious Movement'), ('copy_paste', 'Copy/Paste Detected'), ('right_click', 'Right Click Attempt'), ('keyboard_shortcut', 'Keyboard Shortcut'), ('fullscreen_exit', 'Fullscreen Exit'), ('mobile_device', 'Mobile Device Detected'), ('vpn_detected', 'VPN Detected'), ('unusual_activity', 'Unusual Activity')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='proctoring_screenshots/')),
                ('camera_snapshot', models.ImageField(blank=True, null=True, upload_to='proctoring_camera/')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proctoring.proctoringsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('warning', 'Warning'), ('suspicious', 'Suspicious Activity'), ('cheating_detected', 'Cheating Detected'), ('technical_issue', 'Technical Issue'), ('session_terminated', 'Session Terminated')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='proctoring.proctoringsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_webcam', models.BooleanField(default=True)),
                ('enable_screen_recording', models.BooleanField(default=False)),
                ('enable_tab_detection', models.BooleanField(default=True)),
                ('enable_face_detection', models.BooleanField(default=True)),
                ('enable_audio_monitoring', models.BooleanField(default=False)),
                ('max_tab_switches', models.IntegerField(default=3)),
                ('max_face_detection_failures', models.IntegerField(default=5)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('auto_terminate_on_violation', models.BooleanField(default=False)),
                ('violation_threshold', models.IntegerField(default=10)),
                ('notify_teacher_on_violation', models.BooleanField(default=True)),
                ('allow_teacher_intervention', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
