# Generated by Django 4.2.7 on 2026-04-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_answer_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_marks_threshold', models.FloatField(default=0.8, help_text='Minimum similarity percentage for full marks (0.0-1.0)')),
                ('partial_marks_threshold', models.FloatField(default=0.6, help_text='Minimum similarity percentage for partial marks (0.0-1.0)')),
                ('minimum_marks_threshold', models.FloatField(default=0.4, help_text='Minimum similarity percentage for minimum marks (0.0-1.0)')),
                ('full_marks_percentage', models.FloatField(default=100.0, help_text='Percentage of marks to award for full similarity')),
                ('partial_marks_percentage', models.FloatField(default=50.0, help_text='Percentage of marks to award for partial similarity')),
                ('minimum_marks_percentage', models.FloatField(default=25.0, help_text='Percentage of marks to award for minimum similarity')),
                ('keyword_weight', models.FloatField(default=0.4, help_text='Weight for keyword matching (0.0-1.0)')),
                ('concept_weight', models.FloatField(default=0.3, help_text='Weight for concept understanding (0.0-1.0)')),
                ('structure_weight', models.FloatField(default=0.3, help_text='Weight for answer structure (0.0-1.0)')),
                ('enable_grace_marks', models.BooleanField(default=True)),
                ('grace_marks_percentage', models.FloatField(default=10.0, help_text='Maximum grace marks percentage')),
                ('borderline_threshold', models.FloatField(default=55.0, help_text='Borderline score threshold for grace marks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scoring Configuration',
                'verbose_name_plural': 'Scoring Configurations',
                'unique_together': {('teacher', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('similarity', 'Similarity Based'), ('keyword', 'Keyword Based'), ('length', 'Length Based'), ('structure', 'Structure Based'), ('custom', 'Custom Rule')], default='similarity', max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text='Rule conditions as JSON')),
                ('action_type', models.CharField(choices=[('add_marks', 'Add Marks'), ('multiply', 'Multiply'), ('set_marks', 'Set Marks'), ('skip_question', 'Skip Question')], default='add_marks', max_length=20)),
                ('action_value', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scoring_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scoringconfiguration')),
            ],
            options={
                'verbose_name': 'Scoring Rule',
                'verbose_name_plural': 'Scoring Rules',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkQuestionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='bulk_uploads/')),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF')], default='excel', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('processed_questions', models.IntegerField(default=0)),
                ('failed_questions', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Question Upload',
                'verbose_name_plural': 'Bulk Question Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionWiseScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(blank=True)),
                ('max_marks', models.FloatField(default=1.0)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('numerical', 'Numerical')], default='short_answer', max_length=20)),
                ('custom_full_threshold', models.FloatField(blank=True, help_text='Custom full marks threshold (overrides global)', null=True)),
                ('custom_partial_threshold', models.FloatField(blank=True, help_text='Custom partial marks threshold (overrides global)', null=True)),
                ('custom_minimum_threshold', models.FloatField(blank=True, help_text='Custom minimum marks threshold (overrides global)', null=True)),
                ('required_keywords', models.TextField(blank=True, help_text='Comma-separated keywords required for full marks')),
                ('evaluation_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('hybrid', 'Hybrid')], default='automatic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scoring_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scoringconfiguration')),
            ],
            options={
                'verbose_name': 'Question Wise Scoring',
                'verbose_name_plural': 'Question Wise Scoring',
                'ordering': ['question_number'],
                'unique_together': {('scoring_config', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict, help_text='Scoring configuration as JSON')),
                ('question_template', models.JSONField(default=dict, help_text='Question-wise scoring template')),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation Template',
                'verbose_name_plural': 'Evaluation Templates',
                'unique_together': {('teacher', 'name')},
            },
        ),
    ]
