# Generated by Django 4.2.7 on 2026-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='PDF or Image of the handwritten answer', null=True, upload_to='handwritten_answers/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='evaluation_data',
            field=models.JSONField(blank=True, null=True, help_text='Detailed AI evaluation data'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='evaluation_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
