# Generated by Django 5.2.8 on 2026-04-08 09:12

import django.core.validators
import django.db.models.deletion
import pdf_analysis.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to=pdf_analysis.models.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('document_type', models.CharField(choices=[('exam_paper', 'Exam Paper'), ('question_bank', 'Question Bank'), ('study_material', 'Study Material'), ('answer_sheet', 'Answer Sheet'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('sentence_count', models.IntegerField(blank=True, null=True)),
                ('paragraph_count', models.IntegerField(blank=True, null=True)),
                ('language_detected', models.CharField(blank=True, max_length=10)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('complexity_score', models.FloatField(blank=True, null=True)),
                ('main_topics', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('detected_questions', models.JSONField(blank=True, default=list)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('question_types', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('auto_summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_version', models.CharField(default='1.0', max_length=10)),
                ('pdf_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='pdf_analysis.pdfdocument')),
            ],
            options={
                'verbose_name': 'PDF Analysis Result',
                'verbose_name_plural': 'PDF Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='PDFProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='pdf_analysis.pdfdocument')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PDFQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_questions', to='pdf_analysis.pdfdocument')),
            ],
            options={
                'verbose_name': 'Extracted Question',
                'verbose_name_plural': 'Extracted Questions',
                'ordering': ['page_number', 'created_at'],
            },
        ),
    ]
