# Generated by Django 6.0.4 on 2026-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='complexity_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='content_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='question_analysis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='score_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pdfanalysisresult',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
